enableMariaDB: true
installElastic: true
#enableElasticDB: true
installKibana: false

mariadb:
  #architecture: replication
  #primary:
  #  persistence:
  #    enabled: true
  #    size: 8Gi
  #secondary:
  #  replicaCount: 2
  #  persistence:
  #    enabled: true
  #    size: 8Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  auth:
    #enabled: false
    rootPassword: "mypass"
    replicationPassword: "mypass"

#elasticsearch:
#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true